import { Product, Category, StoreSettings } from '@/types'

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Tablets', slug: 'tablets', displayOrder: 1, status: 'active' },
  { id: 'cat-2', name: 'Capsules', slug: 'capsules', displayOrder: 2, status: 'active' },
  { id: 'cat-3', name: 'Syrups', slug: 'syrups', displayOrder: 3, status: 'active' },
  { id: 'cat-4', name: 'Injections', slug: 'injections', displayOrder: 4, status: 'active' },
  { id: 'cat-5', name: 'Medical Supplies', slug: 'medical-supplies', displayOrder: 5, status: 'active' },
]

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'PCM500-10',
    name: 'Paracetamol 500mg — Brand A — 10 Tablets',
    categoryId: 'cat-1',
    categoryName: 'Tablets',
    brand: 'ABC Pharma',
    strength: '500mg',
    form: 'Tablet',
    packCount: '10 Tablets',
    mrp: 45.00,
    description: 'High purity analgesics for fever and mild to moderate pain relief. Wholesale strip pack.',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    sku: 'PCM500-20',
    name: 'Paracetamol 500mg — Brand A — 20 Tablets',
    categoryId: 'cat-1',
    categoryName: 'Tablets',
    brand: 'ABC Pharma',
    strength: '500mg',
    form: 'Tablet',
    packCount: '20 Tablets',
    mrp: 85.00,
    description: 'Hospital & retail bulk pack of 20 tablets per box.',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    sku: 'PCM500-B10',
    name: 'Paracetamol 500mg — Brand B — 10 Tablets',
    categoryId: 'cat-1',
    categoryName: 'Tablets',
    brand: 'Apex Laboratories',
    strength: '500mg',
    form: 'Tablet',
    packCount: '10 Tablets',
    description: 'Fast-dissolving anti-pyretic formulation by Apex Labs.',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    sku: 'AMX250-10',
    name: 'Amoxicillin 250mg Capsules',
    categoryId: 'cat-2',
    categoryName: 'Capsules',
    brand: 'XYZ Pharma',
    strength: '250mg',
    form: 'Capsule',
    packCount: '10 Capsules',
    description: 'Broad spectrum antibiotic capsules for bacterial infections.',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    sku: 'AZI500-3',
    name: 'Azithromycin 500mg Tablets',
    categoryId: 'cat-1',
    categoryName: 'Tablets',
    brand: 'Novartis Healthcare',
    strength: '500mg',
    form: 'Tablet',
    packCount: '3 Tablets',
    description: 'Macrolide antibiotic 3-day course pack for respiratory tract infections.',
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    sku: 'CET10-10',
    name: 'Cetirizine 10mg Anti-Allergy',
    categoryId: 'cat-1',
    categoryName: 'Tablets',
    brand: 'Cipla Life',
    strength: '10mg',
    form: 'Tablet',
    packCount: '10 Tablets',
    description: '24-hour non-drowsy allergy relief tablets.',
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=600&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    sku: 'COUGH-100',
    name: 'Expectorant Cough Syrup 100ml',
    categoryId: 'cat-3',
    categoryName: 'Syrups',
    brand: 'HealthCare Plus',
    strength: '100ml',
    form: 'Syrup',
    packCount: '1 Bottle',
    description: 'Fast acting bronchodilator & expectorant syrup for heavy cough relief.',
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    sku: 'SYR-5ML-50',
    name: 'Disposable Syringes 5ml with Needle',
    categoryId: 'cat-5',
    categoryName: 'Medical Supplies',
    brand: 'MedTech Supplies',
    strength: '5ml',
    form: 'Supply',
    packCount: '50 Pieces',
    description: 'Sterile single-use 5ml syringes with ultra-fine 24G needles.',
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const INITIAL_SETTINGS: StoreSettings = {
  businessName: 'Sri Subrahmanya Agencies',
  whatsappNumber: '919493397176',
  contactPhone: '+91 94933 97176',
  logoUrl: '',
}
